# This is a basic workflow to help you get started with Actions

name: flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Insert git sha
        run: |
          sed -i -e "s|GIT_SHA_REPLACE|$GITHUB_SHA|g" lib/config.dart
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.x'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter dartfmt -n --set-exit-if-changed lib
      - run: flutter analyze
      - if: github.event_name == 'push'
        uses: erickzanardo/flutter-gh-pages@v6
